USE HotelColibri;
GO

DROP TABLE IF EXISTS CONSULTA_IA;
DROP TABLE IF EXISTS BITACORA;
DROP TABLE IF EXISTS PAGO;
DROP TABLE IF EXISTS DETALLE_FACTURA;
DROP TABLE IF EXISTS FACTURA;
DROP TABLE IF EXISTS MOVIMIENTO_INVENTARIO;
DROP TABLE IF EXISTS DETALLE_PEDIDO;
DROP TABLE IF EXISTS PEDIDO;
DROP TABLE IF EXISTS RECETA_PRODUCTO;
DROP TABLE IF EXISTS HOUSEKEEPING;
DROP TABLE IF EXISTS EVENTO;
DROP TABLE IF EXISTS ESPACIO_EVENTO;
DROP TABLE IF EXISTS RESERVA_MESA;
DROP TABLE IF EXISTS RESERVA;
DROP TABLE IF EXISTS INVENTARIO;
DROP TABLE IF EXISTS MENU;
DROP TABLE IF EXISTS MESA;
DROP TABLE IF EXISTS HABITACION;
DROP TABLE IF EXISTS CLIENTE;
DROP TABLE IF EXISTS AspNetUserTokens;
DROP TABLE IF EXISTS AspNetUserRoles;
DROP TABLE IF EXISTS AspNetUserLogins;
DROP TABLE IF EXISTS AspNetUserClaims;
DROP TABLE IF EXISTS AspNetRoleClaims;
DROP TABLE IF EXISTS AspNetUsers;
DROP TABLE IF EXISTS AspNetRoles;
DROP TABLE IF EXISTS __EFMigrationsHistory;
GO
